version: "3.8"
services:
  ollama-webui:
    networks:
      - net
    image: ghcr.io/ollama-webui/ollama-webui:main
    expose:
      #- "3000"
      - "8080"
    container_name: ollama-webui
    volumes:
      - ollama-webui:/app/backend/data
    #ports:
    #  - 3000:8080
    environment:
      - OLLAMA_API_BASE_URL=http://gpuluck.phonkd.net:11434/api
    #    extra_hosts:
    #     - host.docker.internal:host-gateway
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.lama.entrypoints=https
      - traefik.http.routers.lama.tls.certresolver=letsencrypt
      - traefik.http.routers.lama.rule=Host(`lama.docker.phonkd.net`)
      - traefik.http.routers.lama.tls=true
      - traefik.http.routers.lama.middlewares=authelia@docker
      - traefik.http.routers.lama.tls.certresolver=cloudflare
volumes:
  ollama-webui: {}
networks:
  traefik:
    name: traefik
  net:
    external: true
