version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    #ports:
    #  - 8081:8081
    volumes:
      - /data/immich/dlp:/downloads
    networks:
      - net
    labels:
      - traefik.enable=true
      - traefik.http.routers.dlp.rule=Host(`dlp.docker.phonkd.net`)
      - traefik.http.routers.dlp.entryPoints=https
      - traefik.http.routers.dlp.tls=true
      - traefik.http.routers.dlp.tls.certresolver=cloudflare
      - traefik.http.services.dlp.loadBalancer.server.port=8081
networks:
  net:
    external: true
