apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-grafana
  labels:
    usecase: grafana
spec:
  storageClassName: nfs
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/grafana
    server: 192.168.1.136
