version: "3.8"
networks:
  net:
    driver: bridge
    name: net
  net-affine:
    external: true
services:
  traefik:
    container_name: traefik
    image: traefik:v2.9
    restart: unless-stopped
    command:
      - --api=true
      - --api.dashboard=true
      - --api.insecure=false
      - --pilot.dashboard=false
      - --global.sendAnonymousUsage=false
      - --global.checkNewVersion=false
      - --log=true
      - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entryPoints.http=true
      - --entryPoints.http.address=:8080/tcp
      - --entryPoints.http.http.redirections.entryPoint.to=https
      - --entryPoints.http.http.redirections.entryPoint.scheme=https
      - --certificatesresolvers.cloudflare.acme.email=$CF_APIMAIL
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --entryPoints.http.forwardedHeaders.trustedIPs=10.0.0.0/8,172.16.0.0/16,192.168.0.0/16,fc00::/7
      - --entryPoints.http.proxyProtocol.trustedIPs=10.0.0.0/8,172.16.0.0/16,192.168.0.0/16,fc00::/7
      - --entryPoints.http.forwardedHeaders.insecure=false
      - --entryPoints.http.proxyProtocol.insecure=false
      - --entryPoints.https=true
      - --entryPoints.https.address=:8443/tcp
      - --entryPoints.https.forwardedHeaders.trustedIPs=10.0.0.0/8,172.16.0.0/16,192.168.0.0/16,fc00::/7
      - --entryPoints.https.proxyProtocol.trustedIPs=10.0.0.0/8,172.16.0.0/16,192.168.0.0/16,fc00::/7
      - --entryPoints.https.forwardedHeaders.insecure=false
      - --entryPoints.https.proxyProtocol.insecure=false
      - --entryPoints.http.http.redirections.entryPoint.to=443 ## Forbidden line to fix 844
    environment:
      - CF_API_EMAIL=$CF_APIMAIL
      - CF_DNS_API_TOKEN=$CF_DNS_APITOKEN
    networks:
      net: {}
      net-affine: null
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/traefik/traefik-config:/config
      - /data/traefik/letsencrypt:/letsencrypt
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`traefik.docker.phonkd.net`)
      - traefik.http.routers.api.entryPoints=https
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.tls.certresolver=cloudflare
      - traefik.http.routers.api.middlewares=authelia@docker
  authelia:
    container_name: authelia
    image: authelia/authelia
    restart: unless-stopped
    networks:
      net: {}
      net-affine:
    expose:
      - 9091
    volumes:
      - /data/authelia/authelia-config:/config
    environment:
      TZ: Europe/Zurich
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.rule=Host(`auth.docker.phonkd.net`)
      - traefik.http.routers.authelia.entryPoints=https
      - traefik.http.routers.authelia.tls=true
      - traefik.http.routers.authelia.tls.certresolver=cloudflare
      - traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/verify?rd=https%3A%2F%2Fauth.docker.phonkd.net%2F
      - traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true
      - traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email
      - traefik.http.middlewares.authelia-basic.forwardAuth.address=http://authelia:9091/api/verify?auth=basic
      - traefik.http.middlewares.authelia-basic.forwardAuth.trustForwardHeader=true
      - traefik.http.middlewares.authelia-basic.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email
      - traefik.http.routers.authelia.middlewares=ip-whitelist@docker
      - traefik.http.middlewares.ip-whitelist.ipwhitelist.sourcerange=127.0.0.1/32,
        192.168.1.0/24, 92.106.79.2
