apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mc-pv
  namespace: mc20
  labels:
    usecase: minecraft
spec:
  storageClassName: nfs
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/minecraft_server
    server: 192.168.1.136
