version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    #user: uid:gid
    #network_mode: 'host'
    volumes:
      - /home/phonkd/git/homelab/compose/jellyfin/config:/config
      - /data/nextcloud-data/data/phonkd/files/jellyfin:/media:ro
      #- /path/to/media2:/media2:ro
    restart: unless-stopped
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://jf.docker.phonkd.net
    networks:
      - net
    labels:
      - traefik.enable=true
      - traefik.http.routers.jf.rule=Host(`jf.docker.phonkd.net`)
      - traefik.http.routers.jf.entryPoints=https
      - traefik.http.routers.jf.tls=true
      - traefik.http.routers.jf.tls.certresolver=cloudflare
      - traefik.http.services.jf.loadBalancer.server.port=8096
      - traefik.http.routers.jf.middlewares=ip-whitelist@docker
      - traefik.http.middlewares.ip-whitelist.ipwhitelist.sourcerange=127.0.0.1/32, 192.168.1.0/24, 92.106.79.2
networks:
  net:
    external: true
