version: "3.8"
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - /home/phonkd/git/portainer-services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      #- /data/observability/prometheus/data:/prometheus
    restart: unless-stopped
    expose:
      - "9090"
    networks:
      - net
    #labels:
      #- traefik.enable=true
      #- traefik.http.routers.prom.rule=Host(`prom.docker.phonkd.net`)
      #- traefik.http.routers.prom.entryPoints=https
      #- traefik.http.routers.prom.tls=true
      #- traefik.http.routers.prom.tls.certresolver=cloudflare
      #- traefik.http.services.dashboard.loadBalancer.server.port=9090
networks:
  net:
    external: true
