version: "3.8"
services:
  prometheus:
    image: prom/prometheus
    #ports:
    #  - 9090:9090
    volumes:
      - /home/phonkd/git/homelab/compose/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /data/prometheus-data/:/prometheus
    restart: unless-stopped
    expose:
      - "9090"
    networks:
      - net
    labels:
      - traefik.enable=true
      - traefik.http.routers.prom.rule=Host(`prom.docker.phonkd.net`)
      - traefik.http.routers.prom.entryPoints=https
      - traefik.http.routers.prom.tls=true
      - traefik.http.routers.prom.tls.certresolver=cloudflare
      - traefik.http.services.dashboard.loadBalancer.server.port=9090
      - traefik.http.routers.prom.middlewares=ip-whitelist@docker
      - traefik.http.middlewares.ip-whitelist-int.ipwhitelist.sourcerange=127.0.0.1/32,
        192.168.1.0/24, 92.106.79.2, 10.0.0.0/24
  grafana:
    image: grafana/grafana
    #ports:
    #  - 3000:3000
    volumes:
      - /data/grafana-data:/var/lib/grafana
      - /data/secrets/grafana/grafana.ini:/etc/grafana/grafana.ini
    restart: unless-stopped
    networks:
      - net
    labels:
      - traefik.enable=true
      - traefik.http.routers.graf.rule=Host(`grafana.docker.phonkd.net`)
      - traefik.http.routers.graf.entryPoints=https
      - traefik.http.routers.graf.tls=true
      - traefik.http.routers.graf.tls.certresolver=cloudflare
      - traefik.http.services.graf.loadBalancer.server.port=3000
      - traefik.http.routers.graf.middlewares=ip-whitelist@docker
      - traefik.http.middlewares.ip-whitelist-int.ipwhitelist.sourcerange=127.0.0.1/32,
        192.168.1.0/24, 92.106.79.2, 10.0.0.0/24
networks:
  net:
    external: true
