scrape_configs:
  - job_name: mystrom
    scrape_interval: 30s
    metrics_path: /device
    honor_labels: true
    static_configs:
    - targets:
      - '10.0.0.141'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: mystromexporter:9452
  - job_name: 'pve'
    static_configs:
      - targets:
          - 192.168.1.46 # Proxmox VE node with PVE exporter (without port).
        labels:
          cluster: '1'
          node: '1'
    metrics_path: /pve
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus-pve-exporter:9221  # PVE exporter.
  - job_name: "docker-host"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["10.0.0.130:9100"]
    metrics_path: /metrics
  - job_name: docker
      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.

    static_configs:
      - targets: ["10.0.0.130:9323"]
  - job_name: 'pihole'
    static_configs:
      - targets: ['10.0.0.130:9617']
