grafana:
  # username is 'admin'
  adminPassword: prom-operator
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts: ['grafana.phonkd.net']
    path: "/"
    tls:
    - secretName: cloudflare-api-token-secret
      hosts:
      - grafana.phonkd.net
  defaultDashboardsEnabled: false
  persistence:
   type: pvc
   enabled: true
   storageClassName: longhorn
   accessModes:
    - ReadWriteOnce
   size: 10Gi
  # annotations: {}
   finalizers:
    - kubernetes.io/pvc-protection
prometheus:
  ingress:
      ingressClassName: nginx
      enabled: true
      hosts:
        - prometheus.phonkd.net
      #   - domain.com/prometheus
  persistence:
    type: pvc
    enabled: true
    storageClassName: longhorn
    accessModes: ReadWriteOnce
    size: 20Gi

      
  additionalScrapeConfigsSecret:
    enabled: true
    name: additional-scrape-configs
    key: scrapeconfig.yml

